name: Release

on: [push, pull_request]

jobs:
  build:

    runs-on: [windows-2019]

    env:
      LANG: de_DE.UTF-8

    steps:

    - name: Add msys2 to path
      shell: bash
      run: |
        echo "C:\msys64" >> $GITHUB_PATH
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw64\usr\bin" >> $GITHUB_PATH


    - name: Install additional software
      run: |
        choco install mingw --version 11.2.0.07112021 --allow-downgrade
        choco install ninja

        #- name: Check for executable files
        #  run: |
        #    echo xxxxxxxxxxxxxxxxxxx
        #    $Env:Path
        #    echo xxxxxxxxxxxxxxxxxxx
        #    Get-ChildItem C:\msys64\mingw64\bin\
        #    echo xxxxxxxxxxxxxxxxxxx
        #    (Get-Command aspell).Path
        #    echo xxxxxxxxxxxxxxxxxxx
        #    aspell.exe -h
        #    echo xxxxxxxxxxxxxxxxxxx
        #    (Get-Command pdftotext.exe).Path
        #    echo xxxxxxxxxxxxxxxxxxx
        #    pdftotext.exe -h

    - name: Checkout
      uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2

    #- name: Prepare pdfium build 1
    #  run: |
    #    mkdir -p pdfium
    #    cd pdfium
    #    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    #  shell: bash

    #- name: Prepare pdfium build 2
    #  run: |
    #    cd pdfium
    #    $env:Path += ';.\depot_tools'
    #    $env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
    #    gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
    #    gclient sync --no-history
    #    cd pdfium
    #    gn gen out/Default

    #- name: Prepare pdfium build 3
    #  run: |
    #    bash assets/build_pdfium_static.sh
    #  shell: bash

    #- name: Build pdfium
    #  run: |
    #    $env:Path += ';.\depot_tools'
    #    $env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
    #    cd pdfium/pdfium
    #    ninja -C out/Default pdfium

    - name: Setup toolchain
      run: |
        rustup toolchain install stable-gnu --no-self-update
        rustup default stable-gnu
        cargo --version
        rustup show
        rustup toolchain list
        rustup target list

    - name: Get base pdf
      run: wget https://www.orimi.com/pdf-test.pdf
      shell: bash

    - name: Get pdfium static lib
      run: |
        wget https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-win-x86.tgz
        tar xfvz pdfium-win-x86.tgz

    - name: Build and run
      run: |
        cp lib/pdfium.dll.lib ./pdfium.lib
        #export PDFIUM_STATIC_LIB_PATH="${PWD}/pdfium/pdfium/out/Default/obj"
        file pdfium.lib
        #export PDFIUM_STATIC_LIB_PATH="${PWD}"
        cargo build -vv
        cargo run
      shell: bash

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: tiletest.pdf
        path: tiletest.pdf
